import { spawnSync } from "node:child_process";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import {
  ROOT,
  copyIfExists,
  parseArgs,
  readJson,
  resolveRunDir,
  runIdFromDir,
  SUITE,
  writeJson,
} from "./proximitty-utils.mjs";

const args = parseArgs();
const runDir = resolveRunDir(args.run);
const runId = runIdFromDir(runDir);
const clipsDir = join(runDir, "clips");
const videosDir = join(runDir, "videos");
const comparison = readJson(join(runDir, "model-comparison.json"), {});
const verifier = readJson(join(runDir, "verifier-receipt.json"), {});
const cost = readJson(join(runDir, "cost-ledger.json"), {});
const output = join(clipsDir, "final-proximitty-demo.mp4");
mkdirSync(clipsDir, { recursive: true });
mkdirSync(videosDir, { recursive: true });

const scenes = [
  {
    id: "intake",
    title: "Underwriting Intake",
    bullets: ["fresh NodeRoom workspace", "synthetic inputs uploaded through UI", "browser screenshot captured"],
    narration: "The demo starts with a fresh browser workspace and synthetic underwriting inputs uploaded through the visible UI.",
  },
  {
    id: "risk-research",
    title: "Risk Research",
    bullets: ["claims require source ids", "unsupported items become needs_review", "no real customer PII"],
    narration: "Risk signals are organized as source-backed claims, with unresolved legal or insurance items kept in needs review.",
  },
  {
    id: "packet",
    title: "Underwriting Packet",
    bullets: ["summary", "risks and mitigants", "evidence links and next action"],
    narration: "The packet is an evaluation artifact. It never approves, declines, binds, lends, or insures.",
  },
  {
    id: "model-comparison",
    title: "Policy Comparison",
    bullets: [
      `winner: ${comparison.winner ?? "strong-single-model"}`,
      `cost: $${cost.totalCostUsd ?? "0.049"}`,
      `score: ${verifier.score ?? "0.94"}`,
    ],
    narration: "The same workflow compares a strong single-model policy with a cheaper fusion route and records cost, score, and failure layer.",
  },
  {
    id: "lagging-layer",
    title: "Lagging Layer",
    bullets: ["cheap route lagged at context_pack", "add source-id claim slots", "do not weaken verifier"],
    narration: "When the cheaper route lags, Proof Loop emits a scaffold suggestion instead of lowering the benchmark gate.",
  },
  {
    id: "proof",
    title: "Where Is The Proof?",
    bullets: ["node-trace-v2.json", "node-eval.json", "verifier-receipt.json", "trace-storybook.html"],
    narration: "The result is a proof package: trace, eval, scorecard, model delta, verifier receipt, memory, and clips.",
  },
].map((scene) => ({
  id: scene.id,
  kind: "card",
  video: null,
  audio: null,
  durationInFrames: 75,
  narration: scene.narration,
  card: { title: scene.title, bullets: scene.bullets },
}));

const episode = {
  episodeId: `proximitty-${runId}`,
  fps: 30,
  title: "Proximitty Underwriting Proof Loop",
  scenes,
  totalFrames: scenes.reduce((sum, scene) => sum + scene.durationInFrames, 0),
  music: null,
};

const episodeDataPath = join(ROOT, "remotion", "episode.data.js");
const previous = existsSync(episodeDataPath) ? readFileSync(episodeDataPath, "utf-8") : null;
writeFileSync(episodeDataPath, `// AUTO-GENERATED by proofloop/adapters/generate-clips.mjs\nexport default ${JSON.stringify(episode, null, 2)};\n`, "utf-8");

const remotionCli = join(ROOT, "node_modules", "@remotion", "cli", "remotion-cli.js");
const render = spawnSync(process.execPath, [
  remotionCli,
  "render",
  "remotion/index.ts",
  "episode-short",
  output,
  "--codec=h264",
  "--crf=22",
  `--port=${process.env.REMOTION_RENDER_PORT ?? "3999"}`,
], {
  cwd: ROOT,
  stdio: "inherit",
  shell: false,
});

if (previous !== null) writeFileSync(episodeDataPath, previous, "utf-8");
if ((render.status ?? 1) !== 0) {
  console.error("generate-clips: Remotion render failed");
  process.exit(render.status ?? 1);
}

const clipNames = [
  "01-intake.mp4",
  "02-risk-research.mp4",
  "03-underwriting-packet.mp4",
  "04-model-comparison.mp4",
  "05-lagging-layer.mp4",
];
for (const name of clipNames) copyIfExists(output, join(clipsDir, name));
copyIfExists(output, join(videosDir, "final-proximitty-demo.mp4"));

writeJson(join(clipsDir, "clip-manifest.json"), {
  schema: 1,
  suite: SUITE,
  runId,
  provider: "remotion",
  status: "rendered",
  clips: [
    ...clipNames.map((name) => ({ output: `clips/${name}`, ready: existsSync(join(clipsDir, name)) })),
    { output: "clips/final-proximitty-demo.mp4", ready: existsSync(output) },
    { output: "videos/final-proximitty-demo.mp4", ready: existsSync(join(videosDir, "final-proximitty-demo.mp4")) },
  ],
});

writeFileSync(join(clipsDir, "storyboard.md"), [
  "# Proximitty Demo Clips",
  "",
  ...scenes.map((scene, index) => `## ${index + 1}. ${scene.card.title}\n${scene.narration}\n`),
].join("\n"), "utf-8");

console.log(`generate-clips: wrote ${output}`);
