/**
 * Cypher export — Neo4j interop without a bundled server.
 *
 * Bring-your-own-server rule (docs/architecture/CODE_GRAPH_SUBSTRATE.md): connecting
 * to a user-installed Neo4j over Bolt is arm's-length and safe; bundling the GPLv3
 * Neo4j server is the line not to cross. So this adapter emits a .cypher script the
 * user can load into THEIR server (cypher-shell < export.cypher); we never ship one.
 */
import type { GraphBackend } from "../ports/backend";

export function exportToCypher(backend: GraphBackend): string {
  const lines: string[] = [
    "// Code-graph export — generated by `proofloop graph export-cypher`.",
    "// Load into a user-provided Neo4j server (bring-your-own-server rule:",
    "// docs/architecture/CODE_GRAPH_SUBSTRATE.md — never a bundled server).",
    "// Idempotent: MERGE on node/edge ids; temporal + provenance fields on every fact.",
    "",
  ];
  for (const node of backend.allNodes()) {
    lines.push(
      `MERGE (n:CodeNode {id: '${escapeCypher(node.id)}'}) SET ` +
        `n.kind = '${escapeCypher(node.kind)}', ` +
        `n.label = '${escapeCypher(node.label)}', ` +
        `n.filePath = '${escapeCypher(node.filePath)}', ` +
        (node.detail === undefined ? "" : `n.detail = '${escapeCypher(node.detail)}', `) +
        `n.indexRunId = '${escapeCypher(node.provenance.indexRunId)}', ` +
        `n.commit = '${escapeCypher(node.provenance.commit)}', ` +
        `n.source = '${escapeCypher(node.provenance.source)}';`,
    );
  }
  lines.push("");
  for (const edge of backend.allEdges(false)) {
    const relType = edge.kind.toUpperCase();
    lines.push(
      `MATCH (a:CodeNode {id: '${escapeCypher(edge.from)}'}) ` +
        `MATCH (b:CodeNode {id: '${escapeCypher(edge.to)}'}) ` +
        `MERGE (a)-[r:${relType} {id: '${escapeCypher(edge.id)}'}]->(b) SET ` +
        `r.validFromCommit = '${escapeCypher(edge.validFromCommit)}', ` +
        `r.invalidatedAtCommit = ${edge.invalidatedAtCommit === null ? "null" : `'${escapeCypher(edge.invalidatedAtCommit)}'`}, ` +
        `r.firstIndexedAt = '${escapeCypher(edge.firstIndexedAt)}', ` +
        `r.lastIndexedAt = '${escapeCypher(edge.lastIndexedAt)}', ` +
        `r.indexRunId = '${escapeCypher(edge.provenance.indexRunId)}', ` +
        `r.commit = '${escapeCypher(edge.provenance.commit)}', ` +
        `r.source = '${escapeCypher(edge.provenance.source)}';`,
    );
  }
  lines.push("");
  return lines.join("\n");
}

function escapeCypher(value: string): string {
  return value.replace(/\\/g, "\\\\").replace(/'/g, "\\'");
}
